const locaisPreConfigurados = [
  { id: 1, nome: "Lisboa", tipo: "cidade" },
  { id: 2, nome: "Porto", tipo: "cidade" },
  { id: 3, nome: "Amadora", tipo: "cidade" },
  { id: 4, nome: "Braga", tipo: "cidade" },
  { id: 5, nome: "Coimbra", tipo: "cidade" },
  { id: 6, nome: "Funchal", tipo: "cidade" },
  { id: 7, nome: "Leiria", tipo: "cidade" },
  { id: 8, nome: "Aveiro", tipo: "cidade" },
  { id: 9, nome: "Setúbal", tipo: "cidade" },
  { id: 10, nome: "Vila Nova de Gaia", tipo: "cidade" },
  { id: 11, nome: "Évora", tipo: "cidade" },
  { id: 12, nome: "Viseu", tipo: "cidade" },
  { id: 13, nome: "Barreiro", tipo: "cidade" },
  { id: 14, nome: "Cascais", tipo: "cidade" },
  { id: 15, nome: "Odivelas", tipo: "cidade" },
  { id: 16, nome: "Matosinhos", tipo: "cidade" },
  { id: 17, nome: "Sintra", tipo: "cidade" },
  { id: 18, nome: "Faro", tipo: "cidade" },
  { id: 19, nome: "Guimarães", tipo: "cidade" },
  { id: 20, nome: "Torres Vedras", tipo: "cidade" },
  { id: 21, nome: "Almada", tipo: "cidade" },
  { id: 22, nome: "Tomar", tipo: "cidade" },
  { id: 23, nome: "Viana do Castelo", tipo: "cidade" },
  { id: 24, nome: "Ponta Delgada", tipo: "cidade" },
  { id: 25, nome: "Loulé", tipo: "cidade" },
  { id: 26, nome: "Seixal", tipo: "cidade" },
  { id: 27, nome: "Montijo", tipo: "cidade" },
  { id: 28, nome: "Oliveira de Azeméis", tipo: "cidade" },
  { id: 29, nome: "Santa Maria da Feira", tipo: "cidade" },
  { id: 30, nome: "Loures", tipo: "cidade" },
  { id: 31, nome: "Maia", tipo: "cidade" },
  { id: 32, nome: "Póvoa de Varzim", tipo: "cidade" },
  { id: 33, nome: "Amarante", tipo: "cidade" },
  { id: 34, nome: "Covilhã", tipo: "cidade" },
  { id: 35, nome: "Penafiel", tipo: "cidade" },
  { id: 36, nome: "Lagos", tipo: "cidade" },
  { id: 37, nome: "Figueira da Foz", tipo: "cidade" },
  { id: 38, nome: "Portimão", tipo: "cidade" },
  { id: 39, nome: "Trofa", tipo: "cidade" },
  { id: 40, nome: "Vila Real", tipo: "cidade" },
  { id: 41, nome: "Santarém", tipo: "cidade" },
  { id: 42, nome: "Caldas da Rainha", tipo: "cidade" },
  { id: 43, nome: "Vizela", tipo: "cidade" },
  { id: 44, nome: "Oeiras", tipo: "cidade" },
  { id: 45, nome: "Palmela", tipo: "cidade" },
  { id: 46, nome: "Silves", tipo: "cidade" },
  { id: 47, nome: "Marinha Grande", tipo: "cidade" },
  { id: 48, nome: "Sines", tipo: "cidade" },
  { id: 49, nome: "Espinho", tipo: "cidade" },
  { id: 50, nome: "Estarreja", tipo: "cidade" },
  { id: 51, nome: "São João da Madeira", tipo: "cidade" },
  { id: 52, nome: "Monção", tipo: "cidade" },
  { id: 53, nome: "Vila do Conde", tipo: "cidade" },
  { id: 54, nome: "Alcobaça", tipo: "cidade" },
  { id: 55, nome: "Moita", tipo: "cidade" },
  { id: 56, nome: "Elvas", tipo: "cidade" },
  { id: 57, nome: "Valongo", tipo: "cidade" },
  { id: 58, nome: "Felgueiras", tipo: "cidade" },
  { id: 59, nome: "Entroncamento", tipo: "cidade" },
  { id: 60, nome: "Sesimbra", tipo: "cidade" },
  { id: 61, nome: "Ílhavo", tipo: "cidade" },
  { id: 62, nome: "Ourém", tipo: "cidade" },
  { id: 63, nome: "Ovar", tipo: "cidade" },
  { id: 64, nome: "Chaves", tipo: "cidade" },
  { id: 65, nome: "Pombal", tipo: "cidade" },
  { id: 66, nome: "Castelo Branco", tipo: "cidade" },
  { id: 67, nome: "Fundão", tipo: "cidade" },
  { id: 68, nome: "Beja", tipo: "cidade" },
  { id: 69, nome: "Vendas Novas", tipo: "cidade" },
  { id: 70, nome: "Vila Franca de Xira", tipo: "cidade" },
  { id: 71, nome: "Almeirim", tipo: "cidade" },
  { id: 72, nome: "Fafe", tipo: "cidade" },
  { id: 73, nome: "Fronteira", tipo: "cidade" },
  { id: 74, nome: "Albufeira", tipo: "cidade" },
  { id: 75, nome: "Vila Nova de Famalicão", tipo: "cidade" },
  { id: 76, nome: "Marco de Canaveses", tipo: "cidade" },
  { id: 77, nome: "Alcochete", tipo: "cidade" },
  { id: 78, nome: "Caminha", tipo: "cidade" },
  { id: 79, nome: "Castelo de Paiva", tipo: "cidade" },
  { id: 80, nome: "Alijó", tipo: "cidade" },
  { id: 81, nome: "Fornos de Algodres", tipo: "cidade" },
];

module.exports = locaisPreConfigurados;
