name: Deploy Backend to VPS

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: root
          REMOTE_HOST: 147.79.87.223
          PM2_APP_NAME: server
          REMOTE_BACKEND_PATH: /var/www/backends/ondish
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $REMOTE_USER@$REMOTE_HOST "
            cd $REMOTE_BACKEND_PATH &&
            git stash &&
            git pull origin prod &&
            git stash pop || true &&
            npm install &&
            pm2 reload $PM2_APP_NAME || pm2 start server.js --name $PM2_APP_NAME
          "
          